-- V1 — Esquema inicial de FusaRoute: usuarios y catalogo de rutas.
--
-- Flyway es el dueno del esquema (SCRUM-161). Las tablas se crean SIN calificar
-- con el nombre del esquema a proposito: Flyway ya posiciona el esquema por
-- defecto desde 'spring.flyway.schemas', y asi la misma migracion sirve en DEV,
-- PRE y PROD sin editarla.
--
-- Las reglas de negocio que sostienen estas tablas estan en el CLAUDE.md del
-- backend y en docs/backlog/historias-rf01-rf15.md de la carpeta del curso.


-- ---------------------------------------------------------------------------
-- users — usuario final y administrador (RF-01, RF-02, RF-03)
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(120)  NOT NULL,
    email                 VARCHAR(180)  NOT NULL,
    -- BCrypt produce siempre 60 caracteres; 72 deja aire sin invitar a guardar
    -- nada mas largo. La contrasena en claro no entra aqui jamas.
    password_hash         VARCHAR(72)   NOT NULL,
    -- Editable en el perfil y opcional en el registro (RF-03).
    phone                 VARCHAR(30),
    role                  VARCHAR(20)   NOT NULL DEFAULT 'USER',
    -- Hasta 4 intentos fallidos con mensaje generico; al quinto, bloqueo
    -- temporal con aviso explicito (RF-02). El contador vive en la fila del
    -- usuario y no en memoria para que el bloqueo sobreviva a un reinicio.
    failed_login_attempts SMALLINT      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_failed_attempts CHECK (failed_login_attempts >= 0)
);

COMMENT ON TABLE users IS
    'Usuario final o administrador. La autenticacion es propia (Spring Security + JWT), no Supabase Auth.';


-- ---------------------------------------------------------------------------
-- routes — catalogo de rutas de buseta (RF-04, RF-05, RF-06, RF-11)
-- ---------------------------------------------------------------------------
-- Una ruta es un recorrido DIRECTO de un solo tramo: no hay transbordos, y el
-- recorrido de ida y el de vuelta son DOS registros independientes, no un mismo
-- registro con "sentido".
--
-- Hoy la semilla carga UN SOLO SENTIDO de cada ruta. Eso no cambia el modelo:
-- cuando entre el sentido contrario es una fila mas, no una columna 'sentido'
-- ni un cambio de esquema. Se deja dicho aqui para que nadie lo reinterprete.
CREATE TABLE routes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(140) NOT NULL,
    route_type    VARCHAR(20)  NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVA',
    -- Trazado GeoJSON (LineString). Es dato propio del proyecto, no de Google:
    -- Google solo cronometra rutas que el dominio ya filtro. jsonb y no text
    -- para que Postgres valide que es JSON bien formado al insertar.
    --
    -- NULLABLE a proposito: la busqueda de RF-04/05/06 filtra las rutas
    -- candidatas por NOMBRE DE BARRIO, asi que no necesita el trazado. El
    -- trazado lo necesitan el mapa (SCRUM-154) y el modo offline, que calcula
    -- la mejor ruta por distancia geometrica sobre el GeoJSON. Una ruta con
    -- path_geojson NULL se puede buscar y listar, y es invisible para el
    -- offline. Los trazados llegan en su propio issue.
    path_geojson  JSONB,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_routes_name UNIQUE (name),
    CONSTRAINT ck_routes_type CHECK (route_type IN ('URBANA', 'INTERMUNICIPAL')),
    -- 'SUSPENDIDA' es suspension temporal; GET /api/routes filtra solo activas.
    CONSTRAINT ck_routes_status CHECK (status IN ('ACTIVA', 'SUSPENDIDA'))
);

-- El listado del catalogo pide solo las activas, y es la consulta mas frecuente.
CREATE INDEX ix_routes_status ON routes (status);

COMMENT ON TABLE routes IS
    'Ruta de buseta: recorrido directo sin transbordos. Ida y vuelta son dos registros distintos.';


-- ---------------------------------------------------------------------------
-- route_neighborhoods — barrios que atraviesa cada ruta, en orden (RF-05)
-- ---------------------------------------------------------------------------
-- Los barrios se guardan como LISTA DE NOMBRES, no como poligonos: modelar
-- geometria exigiria PostGIS y esta fuera de alcance. El orden es el orden de
-- recorrido y lo valida una persona por inspeccion visual contra el GeoJSON al
-- cargar el dato — no hay validacion geoespacial automatica.
CREATE TABLE route_neighborhoods (
    route_id          BIGINT       NOT NULL,
    order_index       INTEGER      NOT NULL,
    neighborhood_name VARCHAR(120) NOT NULL,

    CONSTRAINT pk_route_neighborhoods PRIMARY KEY (route_id, order_index),
    CONSTRAINT fk_route_neighborhoods_route FOREIGN KEY (route_id)
        REFERENCES routes (id) ON DELETE CASCADE,
    CONSTRAINT ck_route_neighborhoods_order CHECK (order_index >= 0),
    -- Un barrio no se repite dentro de la misma ruta: si aparece dos veces es
    -- un error de carga manual, y esta restriccion lo caza en el momento.
    CONSTRAINT uq_route_neighborhoods_name UNIQUE (route_id, neighborhood_name)
);

-- La busqueda filtra rutas candidatas por barrio de origen y de destino.
CREATE INDEX ix_route_neighborhoods_name ON route_neighborhoods (neighborhood_name);


-- ---------------------------------------------------------------------------
-- fares — costo del pasaje (RF-06)
-- ---------------------------------------------------------------------------
-- Dos formas segun el tipo de ruta:
--   * URBANA: un unico precio fijo por ruta -> una sola fila con
--     reference_point NULL.
--   * INTERMUNICIPAL: tabla de precios por punto de referencia de bajada
--     (no por parada — en Fusagasuga no hay paradas formales, se para con la
--     mano) -> varias filas con reference_point, ordenadas de menor a mayor.
CREATE TABLE fares (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id        BIGINT         NOT NULL,
    -- Pesos colombianos. numeric y no float: el dinero no se representa en
    -- punto flotante binario.
    amount          NUMERIC(10, 2) NOT NULL,
    -- NULL = tarifa unica de una ruta urbana. Con valor = punto de referencia
    -- geografico de bajada de una intermunicipal.
    reference_point VARCHAR(160),
    order_index     INTEGER        NOT NULL DEFAULT 0,
    -- vigente_desde: la pantalla muestra la fecha de ultima actualizacion del
    -- precio (RF-06). Un cambio de tarifa es una fila nueva, no un UPDATE.
    valid_from      DATE           NOT NULL,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT fk_fares_route FOREIGN KEY (route_id)
        REFERENCES routes (id) ON DELETE CASCADE,
    CONSTRAINT ck_fares_amount CHECK (amount > 0),
    CONSTRAINT ck_fares_order CHECK (order_index >= 0),
    -- NULLS NOT DISTINCT (PostgreSQL 15+) hace que el NULL de la tarifa urbana
    -- tambien choque consigo mismo: sin esto, una ruta urbana podria acumular
    -- varias "tarifas unicas" vigentes desde la misma fecha sin que nada falle.
    CONSTRAINT uq_fares_route_point UNIQUE NULLS NOT DISTINCT
        (route_id, reference_point, valid_from)
);

CREATE INDEX ix_fares_route ON fares (route_id);

COMMENT ON TABLE fares IS
    'Tarifa del pasaje. Urbana: una fila con reference_point NULL. Intermunicipal: una fila por punto de bajada.';
